--INTRODUÇAO
No âmbito da disciplina de Redes de Comunicação II foi-nos proposto o desenvolvimento de um trabalho
que simulasse um ambiente de rede com recurso ao Cisco Packet Tracer, com o intuito de adquirir e consolidar 
os conhecimentos lecionados nas aulas teóricas. 
O objetivo é executar configurações básicas em equipamentos como
switches e PC’S, estas configurações passam pelas interfaces Ethernet nos respetivos e a otimização do funcionamento da rede com recurso do Protocolo Spanning Tree que ajuda a resolver problemas de loops em redes comutadas com ligações com topologia anel.
Este relatório está subdividido em várias partes que representam cada uma das questões do enunciado, começamos assim por apresentar a topologia utilizada descriminando as suas configurações, seguindo para os passos propostos e os testes da utilização do protocolo explicando-os devidamente.	
